name: TheGrandTourney
version: '${project.version}'
main: me.genn.thegrandtourney.TGT
api-version: '1.19'
depend:
  - Citizens
  - NBTAPI
  - MagicSpells
  - MythicMobs
  - ProtocolLib
  - WorldEdit
  - SpectralDamage
  - Vault
  - GennsGym


commands:
  testgen:
    description: test generation
  checkcell:
    description: check occupancy of cell
  zap:
    description: zaps to step
  itemtest:
    description: item test
  tgtitem:
    description: give item
  chain:
    description: chain commands together
  conjure:
    description: gives item without message lol
  spawn:
    description: spawns a tgt object
  saveschematic:
    description: saves a schem
  fishing-zone:
    description: defines a fishing zone
  menu:
    description: open menu
  slots:
    description: add slots for bags
  dosh:
    description: add money
  skill-xp:
    description: add skill xp
  tabletest:
    description: table
  grant-recipe:
    description: grants recipe
  stat:
    description: modifies base stats
  foraging-zone:
    description: creates foraging zone
  dungeon:
    description: create dungeon
  room:
    description: creates room
  door:
    description: creates door
  startgame:
    description: Starts the game
  nextgame:
    description: Shows or sets the next game
  override:
    description: Override
  endround:
    description: Ends the round and starts the next one
  roundscoreadd:
    description: Add round score
  gamescoreadd:
    description: Ends the round and starts the next one
  gamescoreset:
    description: Add round score
  roundscoreset:
    description: Sets round score
  playerout:
    description: mark player out
  start-tournament:
    description: starts the tourney
  exit:
    description: creates dungeon exit point or entry point
  reward-chest:
    description: adds reward chest
  points-multiplier:
    description: sets points mult for game
  invshop:
    description: opens shop
  debug:
    description: toggles debug
  temp-stat:
    description: temporarily increases a stat
  potion-effect:
    description: potion buff
  bank:
    description: open bank
  bank-dosh:
    description: add money to bank